"""add kg_mappings table

Revision ID: 7c27daf4c611
Revises: 73bb4c0c43f0
Create Date: 2025-12-04 15:16:27.642381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c27daf4c611'
down_revision = '73bb4c0c43f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='映射类别: entity_type, relation_type, entity_synonym, node_color'),
    sa.Column('source_key', sa.String(length=100), nullable=False, comment='源键 (如: 中文名称)'),
    sa.Column('target_value', sa.String(length=100), nullable=False, comment='目标值 (如: Neo4j类型)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'source_key', name='uq_category_source')
    )
    with op.batch_alter_table('kg_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kg_mappings_category'), ['category'], unique=False)

    op.drop_table('langchain_pg_embedding')
    op.drop_table('langchain_pg_collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_embedding_pkey'))
    )
    with op.batch_alter_table('kg_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kg_mappings_category'))

    op.drop_table('kg_mappings')
    # ### end Alembic commands ###
